# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7b2499e6a371a71f4bc715bb26cee585"
application_url = "https://vialityhealth.com"
embedded = true
name = "Webhooks"

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_discounts"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
